repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        files: ^moodle/.*\.py$
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args:
        - --ignore=E501
-   repo: https://github.com/PyCQA/pylint
    rev: v2.12.2
    hooks:
    -   id: pylint
        files: ^moodle/.*\.py$
        args:
        - --errors-only
        - --disable=import-error
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.971'
    hooks:
    -   id: mypy
        files: ^moodle/.*\.py$